title: NIZHAL
description: The Unknown Frequency

# 1. Theme Setting (This is the fix)
theme: jekyll-theme-minimal

# 2. Allow future posts (Timezone fix)
future: true 

# 3. Setup the Stories Collection
collections:
  stories:
    output: true
    sort_by: date
    permalink: /stories/:year/:month/:day/:title/

# 4. Plugins
plugins:
  - jekyll-feed
