title: NIZHAL
description: The Unknown Frequency

# 1. This enables viewing stories even if time is slightly ahead
future: true 

# 2. Setup the Stories Collection properly
collections:
  stories:
    output: true
    sort_by: date
    permalink: /stories/:year/:month/:day/:title/

# 3. Build Settings
markdown: kramdown
theme: jekyll-theme-prime
plugins:
  - jekyll-feed
