title: NIZHAL
baseurl: "/nizhal-website" # ലിങ്കുകൾ ശരിയാകാൻ ഇത് അത്യാവശ്യമാണ്
url: "https://nizhalstoriesyt.github.io"

theme: minima
future: true

collections:
  stories:
    output: true
    sort_by: date
