title: NIZHAL
baseurl: "/nizhal-website"
url: "https://nizhalstoriesyt.github.io"

theme: minima
future: true

collections:
  stories:
    output: true
    sort_by: date

# ⚠️ ഈ ഭാഗമാണ് പുതിയതായി ചേർത്തത് (Layout Connection)
defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
